dist: trusty
sudo: required

language: node_js
node_js:
  - '12'

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

env:
  global:
    CODECOV_TOKEN=9df3bf68-c500-4c84-b97c-adaaf2b04910

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox --codeCoverage=true

before_install:
  - npm install
  - pip install --user codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  api_key: 8c55cc26-9ec7-4dcc-825a-fbb879174dff
  app: short-url-front-stage

notifications:
  email:
    on_success: never
    on_failure: always
